coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080

node.internal-address=trino

discovery.uri=http://trino:8080

query.max-memory=1300MB
query.max-memory-per-node=1300MB